name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Added'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Changed'
    labels: 
      - 'change'
      - 'update'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
